global using _7oras.Application.Validators;
global using _7oras.Application.Shared.Dtos.Request.Category;
global using _7oras.Application.Shared.Dtos.Response.Category;
global using _7oras.Application.Shared.ISevices;
global using _7oras.Domain;
global using _7oras.Domain.Interfaces;
global using AutoMapper;
global using FluentValidation;
global using Microsoft.Extensions.DependencyInjection;
